# Generated by Django 4.2.14 on 2024-07-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glycemic_index_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterField(
            model_name='note',
            name='glycemic_index',
            field=models.CharField(max_length=500),
        ),
    ]
