# Generated by Django 4.2.14 on 2024-08-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glycemic_index_app', '0002_alter_note_options_alter_note_glycemic_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bu_index',
            field=models.TextField(blank=True),
        ),
    ]
