# Generated by Django 4.2.14 on 2024-08-29 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glycemic_index_app', '0003_customuser_bu_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='glycemia',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='note',
            name='glycemic_index',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
    ]
