# Generated by Django 4.2.14 on 2024-08-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glycemic_index_app', '0005_alter_note_glycemia_alter_note_glycemic_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='absorption_time',
            field=models.TextField(blank=True, default='100,90,80,70,60,50,40,30,20,10'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bu_index',
            field=models.TextField(blank=True, default='2.5'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rcg',
            field=models.TextField(blank=True, default='0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.1'),
        ),
    ]
